# Generated by Django 4.2.6 on 2023-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
